### ISSUE TITLE
Angående laboration 2

### ISSUE THREAD

**Issue by 1dv449** [OskarKlintrotSkolarbeteWP14/1DV449_oklib08#1]
Hej!

Jag har nu tittat på din laboration 2.

På det hela taget en gedigen rapport som visar på god kunskap och uppfyller målen med laborationen. Bra skriven (i alla fall enligt min kunskap om engelska språket) och enkelt att ta till sig. Jag kan i vissa fall (speciellt säkerheten) sakna förslag på åtgärder för att fixa problemen.

Jag sätter upp dig som godkänd på laboration 2.

Det finns ett delat dokument där man kan se de olika delar som skulle kunnat tas upp i rapporten.
https://docs.google.com/document/d/1kYNrL64Od1go4z0_sZUyIG8eFAaeFcdp95MIHsRm65A/edit?usp=sharing

**Comment by OskarKlintrot** [comment]
Tack så mycket för feedbacken, det var en väldigt rolig laboration!
